from pydantic import BaseModel, Field
from typing import Optional

class Imovel(BaseModel):
    id: str = Field(..., alias='_id')
    lat: Optional[float]
    lon: Optional[float]
    usable_areas: Optional[int]
    parking_spaces: Optional[int]
    suites: Optional[int]
    bathrooms: Optional[int]
    total_areas: Optional[int]
    bedrooms: Optional[int]
    geohash: Optional[str]
    price: Optional[int]
    yearly_iptu: Optional[int]
    monthly_condo_fee: Optional[int]
    has_gym: bool
    has_garden: bool
    has_pool: bool
    has_lobby: bool
    has_party_room: bool
    has_balcony: bool
    has_playground: bool
    has_grill: bool
    has_games: bool
    has_closet: bool
    has_elevator: bool
    has_furnitures: bool
    has_toilet: bool
    has_massage_room: bool
    has_washhouse: bool
    has_terrace: bool
    has_pilates: bool
    has_fancy_words: bool
    has_shield: bool
    has_drivers_room: bool
    has_biometry: bool
    has_fireplace: bool
    has_deposit: bool
    has_ceiling_height: bool
    has_generator: bool
    has_pantry: bool
    is_duplex: bool
    is_triplex: bool
    total_dom_part_improvisados: Optional[int]
    renda_nom_dom_part: Optional[int]
    renda_nom_dom_part_perm: Optional[int]
    renda_nom_dom_part_imp: Optional[int]
    renda_nom_dom_sal_baixo1: Optional[int]
    renda_nom_dom_sal_baixo2: Optional[int]
    renda_nom_dom_sal_baixo3: Optional[int]
    renda_nom_dom_sal_baixo4: Optional[int]
    renda_nom_dom_sal_medio1: Optional[int]
    renda_nom_dom_sal_medio2: Optional[int]
    renda_nom_dom_sal_medio3: Optional[int]
    renda_nom_dom_sal_alto1: Optional[int]
    renda_nom_dom_sal_alto2: Optional[int]
    renda_nom_dom_sem_rendimento: Optional[int]
    ident_logradouro_proprios: Optional[int]
    nao_ident_logradouro_proprios: Optional[int]
    ident_logradouro_alugados: Optional[int]
    nao_ident_logradouro_alugados: Optional[int]
    ilum_publica_proprios: Optional[int]
    nao_ilum_publica_proprios: Optional[int]
    ilum_publica_alugados: Optional[int]
    nao_ilum_publica_alugados: Optional[int]