from pydantic import BaseModel

class Apartment(BaseModel):
    usableAreas: int
    parkingSpaces: int
    suites: int
    bathrooms: int
    totalAreas: float
    bedrooms: int
    publicationType: int
    businessType: int
    yearlyIptu: int
    monthlyCondoFee: int
    has_gym: bool
    has_garden: bool
    has_pool: bool
    has_lobby: bool
    has_partyRoom: bool
    has_balcony: bool
    has_playground: bool
    has_grill: bool
    has_games: bool
    has_closet: bool
    has_furnitures: bool
    has_toilet: bool
    total_dom_part_improvisados: int
    renda_nom_dom_part: int
    renda_nom_dom_part_perm: float
    renda_nom_dom_part_imp: int
    renda_nom_dom_sal_baixo1: int
    renda_nom_dom_sal_baixo2: int
    renda_nom_dom_sal_baixo3: int
    renda_nom_dom_sal_baixo4: int
    renda_nom_dom_sal_medio1: int
    renda_nom_dom_sal_medio2: int
    renda_nom_dom_sal_medio3: int
    renda_nom_dom_sal_alto1: int
    renda_nom_dom_sal_alto2: int
    renda_nom_dom_sem_rendimento: int
    ident_logradouro_proprios: int
    nao_ident_logradouro_proprios: int
    ident_logradouro_alugados: int
    nao_ident_logradouro_alugados: int
    ilum_publica_proprios: int
    nao_ilum_publica_proprios: int
    ilum_publica_alugados: int
    nao_ilum_publica_alugados: int
    geohash_5: int